[package]
name = "power-BI"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#命令行解析工具
clap = { version = "4.0.10", features = ["derive"] }
properties = "0.1.1"
lazy_static = "1.4.0"
tera = "1.17.1"